# Data Enrichment

In this notebook, data from other sources will be added to the dataset.

In [1]:
# import required libs
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from urllib import request
import json
from time import sleep

In [2]:
# read original dataset from file
df = pd.read_csv('/home/fede/workspace/DataLab/python/data/payments_w_city_weather.txt', sep='|', header=0, decimal=",")

Now the dataset is loaded in memory as a pandas DataFrame.

The first thing to do is, with the postal code, get the information about the cities: city name, province, autonomous community, country, latitude and longitude; for both the store and the client.

In [3]:
# cache for cities already obtained from gmaps api
distances = {}

In [4]:
# city object with info needed obtained from gmaps
class Distance:
    def __init__(self, distance, duration):
        self.distance = distance
        self.duration = duration

In [5]:
def get_distance_from_maps(lat1, lon1, lat2, lon2):
    maps_url = "https://maps.googleapis.com/maps/api/distancematrix/json?origins={0},{1}&destinations={2},{3}&mode=driving".format(lat1, lon1, lat2, lon2)
    response = request.urlopen(maps_url).read().decode('utf-8')
    json_maps = json.loads(response)
    sleep(0.2)
    print(maps_url)
    try:
        print(json_maps)
        row = json_maps['rows'][0]
        print('ok')
        values = row['elements'][0]
        distance_m = values['distance']['value']
        duration_s = values['duration']['value']
        dist = Distance(distance_m, duration_s)
        return dist
    except:
        print('error')
        return Distance(0, 0)

In [6]:
from math import radians, cos, sin, asin, sqrt
def haversine(lat1, lon1, lat2, lon2):
    """
    Calculate the great circle distance between two points 
    on the earth (specified in decimal degrees)
    """
    # convert decimal degrees to radians 
    lon1, lat1, lon2, lat2 = map(radians, [float(lon1), float(lat1), float(lon2), float(lat2)])
    # haversine formula 
    dlon = lon2 - lon1 
    dlat = lat2 - lat1 
    a = sin(dlat/2)**2 + cos(lat1) * cos(lat2) * sin(dlon/2)**2
    c = 2 * asin(sqrt(a)) 
    km = 6367 * c
    return km

In [7]:
def get_dist_info(lat1, lon1, lat2, lon2):
    conc = str(lat1) + str(lon1) + str(lat2) + str(lon2)
    if conc in distances:
        distance = distances[conc]
    else:
        distance = haversine(lat1, lon1, lat2, lon2)
        distances[conc] = distance
    return {
        "DISTANCE": distance
    }

In [8]:
# get information about distances and add them to the df
distance_cols = pd.DataFrame.from_records(df.apply(lambda row: get_dist_info(row['LAT_CLIENTE'], row['LON_CLIENTE'], row['LAT_COMERCIO'], row['LON_COMERCIO']), axis=1))
df = pd.concat([df, distance_cols], axis=1)

Let's check now how it looks.

In [9]:
df.to_csv('/home/fede/workspace/DataLab/python/data/payments_w_distance.txt', sep='|', index=False,  decimal=".")

In [11]:
df.describe(include='all')

,CP_CLIENTE,CP_COMERCIO,SECTOR,DIA,FRANJA_HORARIA,IMPORTE,NUM_OP,CIUDAD_CLIENTE,LAT_CLIENTE,LON_CLIENTE,...,LAT_COMERCIO,LON_COMERCIO,FECHA,TIMESTAMP,HUMEDAD,SENSAC_TERMICA,TEMPERATURA,TIEMPO_DESC,DIA_SEMANA,DISTANCE
count,3.428537e+06,3.428537e+06,3428537,3428537,3428537,3428537,3.428537e+06,3428537,3428537,3428537,...,3428537,3428537,3428537,3.428537e+06,3428537,3428537,3428537,3428537,3428537,3.428537e+06
unique,NaN,NaN,11,731,12,64674,NaN,224,291,182,...,25,21,8765,NaN,89,2846,2702,9,7,NaN
top,NaN,NaN,ALIMENTACION,2016-01-04,18-20,20.0,NaN,Valencia,39.4417674,-0.39602750000000003,...,39.4845265,-0.380721,2016-01-04 18:00:00,NaN,0.55,19.02,26.99,Despejado,S√ÅBADO,NaN
freq,NaN,NaN,671157,8810,635901,60770,NaN,1626340,99719,197172,...,290102,439073,1845,NaN,95813,7580,7991,2454130,574775,NaN
mean,4.623815e+04,4.601226e+04,NaN,NaN,NaN,NaN,1.444462e+00,NaN,NaN,NaN,...,NaN,NaN,NaN,1.452573e+09,NaN,NaN,NaN,NaN,NaN,1.388909e+01
std,3.053983e+02,7.298001e+00,NaN,NaN,NaN,NaN,1.860094e+00,NaN,NaN,NaN,...,NaN,NaN,NaN,1.833651e+07,NaN,NaN,NaN,NaN,NaN,1.864734e+01
min,4.600100e+04,4.600100e+04,NaN,NaN,NaN,NaN,1.000000e+00,NaN,NaN,NaN,...,NaN,NaN,NaN,1.420067e+09,NaN,NaN,NaN,NaN,NaN,0.000000e+00
25%,4.601700e+04,4.600600e+04,NaN,NaN,NaN,NaN,1.000000e+00,NaN,NaN,NaN,...,NaN,NaN,NaN,1.436544e+09,NaN,NaN,NaN,NaN,NaN,1.987421e+00
50%,4.611700e+04,4.601300e+04,NaN,NaN,NaN,NaN,1.000000e+00,NaN,NaN,NaN,...,NaN,NaN,NaN,1.452791e+09,NaN,NaN,NaN,NaN,NaN,5.528570e+00
75%,4.637000e+04,4.601900e+04,NaN,NaN,NaN,NaN,1.000000e+00,NaN,NaN,NaN,...,NaN,NaN,NaN,1.468246e+09,NaN,NaN,NaN,NaN,NaN,1.770483e+01
max,4.698900e+04,4.602600e+04,NaN,NaN,NaN,NaN,7.100000e+01,NaN,NaN,NaN,...,NaN,NaN,NaN,1.483218e+09,NaN,NaN,NaN,NaN,NaN,1.185994e+02